on: [push, pull_request]
name: Test
jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false
      - run: go test ./...
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
